-- Ingredients

insert into pizzeria.Ingredient (name, prix) values ('ail', 1);
insert into pizzeria.Ingredient (name, prix) values ('ananas', 1);
insert into pizzeria.Ingredient (name, prix) values ('anchois', 1);
insert into pizzeria.Ingredient (name, prix) values ('artichauts', 1);
insert into pizzeria.Ingredient (name, prix) values ('aubergines grillees', 1);
insert into pizzeria.Ingredient (name, prix) values ('bacon', 1);
insert into pizzeria.Ingredient (name, prix) values ('bacon fume', 1);
insert into pizzeria.Ingredient (name, prix) values ('boeuf', 1);
insert into pizzeria.Ingredient (name, prix) values ('boeuf epicee', 1);
insert into pizzeria.Ingredient (name, prix) values ('capres', 1);
insert into pizzeria.Ingredient (name, prix) values ('champignons', 1);
insert into pizzeria.Ingredient (name, prix) values ('cheddar', 1);
insert into pizzeria.Ingredient (name, prix) values ('chorizo', 1);
insert into pizzeria.Ingredient (name, prix) values ('creme fraiche', 1);
insert into pizzeria.Ingredient (name, prix) values ('emince de boeuf', 1);
insert into pizzeria.Ingredient (name, prix) values ('emmental', 1);
insert into pizzeria.Ingredient (name, prix) values ('fourme d\'ambert aop', 1);
insert into pizzeria.Ingredient (name, prix) values ('fromage', 1);
insert into pizzeria.Ingredient (name, prix) values ('fromage a raclette', 1);
insert into pizzeria.Ingredient (name, prix) values ('fromage de chevre', 1);
insert into pizzeria.Ingredient (name, prix) values ('fromage fondu', 1);
insert into pizzeria.Ingredient (name, prix) values ('fromage grimbergen', 1);
insert into pizzeria.Ingredient (name, prix) values ('fromage rapee', 1);
insert into pizzeria.Ingredient (name, prix) values ('fruits de mer', 1);
insert into pizzeria.Ingredient (name, prix) values ('gorgonzola', 1);
insert into pizzeria.Ingredient (name, prix) values ('jambon', 1);
insert into pizzeria.Ingredient (name, prix) values ('jambon italien', 1);
insert into pizzeria.Ingredient (name, prix) values ('lardons fumes', 1);
insert into pizzeria.Ingredient (name, prix) values ('merguez', 1);
insert into pizzeria.Ingredient (name, prix) values ('mozzarella', 1);
insert into pizzeria.Ingredient (name, prix) values ('oeuf', 1);
insert into pizzeria.Ingredient (name, prix) values ('oignons', 1);
insert into pizzeria.Ingredient (name, prix) values ('oignons rouges', 1);
insert into pizzeria.Ingredient (name, prix) values ('olives', 1);
insert into pizzeria.Ingredient (name, prix) values ('origan', 1);
insert into pizzeria.Ingredient (name, prix) values ('pepperoni', 1);
insert into pizzeria.Ingredient (name, prix) values ('persil', 1);
insert into pizzeria.Ingredient (name, prix) values ('piments forts', 1);
insert into pizzeria.Ingredient (name, prix) values ('piments verts', 1);
insert into pizzeria.Ingredient (name, prix) values ('poivrons', 1);
insert into pizzeria.Ingredient (name, prix) values ('poivron vert', 1);
insert into pizzeria.Ingredient (name, prix) values ('pommes de terre', 1);
insert into pizzeria.Ingredient (name, prix) values ('porc epicee', 1);
insert into pizzeria.Ingredient (name, prix) values ('poulet frit', 1);
insert into pizzeria.Ingredient (name, prix) values ('poulet fume', 1);
insert into pizzeria.Ingredient (name, prix) values ('poulet grille', 1);
insert into pizzeria.Ingredient (name, prix) values ('poulet kebab (halal)', 1);
insert into pizzeria.Ingredient (name, prix) values ('provolone', 1);
insert into pizzeria.Ingredient (name, prix) values ('pulled pork', 1);
insert into pizzeria.Ingredient (name, prix) values ('reblochon', 1);
insert into pizzeria.Ingredient (name, prix) values ('sauce a l\'ail', 1);
insert into pizzeria.Ingredient (name, prix) values ('sauce au poivre', 1);
insert into pizzeria.Ingredient (name, prix) values ('sauce barbecue', 1);
insert into pizzeria.Ingredient (name, prix) values ('sauce chili thai', 1);
insert into pizzeria.Ingredient (name, prix) values ('sauce curry douce', 1);
insert into pizzeria.Ingredient (name, prix) values ('sauce tomate', 1);
insert into pizzeria.Ingredient (name, prix) values ('saumon fume', 1);
insert into pizzeria.Ingredient (name, prix) values ('thon', 1);
insert into pizzeria.Ingredient (name, prix) values ('tomate', 1);
insert into pizzeria.Ingredient (name, prix) values ('tomates fraiches', 1);
insert into pizzeria.Ingredient (name, prix) values ('viande de veau fume', 1);
insert into pizzeria.Ingredient (name, prix) values ('viande hachee', 1);
