-- Ingredients

insert into pizzeria.Ingredient (name, price) values ('ail', 1);
insert into pizzeria.Ingredient (name, price) values ('ananas', 1);
insert into pizzeria.Ingredient (name, price) values ('anchois', 1);
insert into pizzeria.Ingredient (name, price) values ('artichauts', 1);
insert into pizzeria.Ingredient (name, price) values ('aubergines grillees', 1);
insert into pizzeria.Ingredient (name, price) values ('bacon', 1);
insert into pizzeria.Ingredient (name, price) values ('bacon fume', 1);
insert into pizzeria.Ingredient (name, price) values ('boeuf', 1);
insert into pizzeria.Ingredient (name, price) values ('boeuf epicee', 1);
insert into pizzeria.Ingredient (name, price) values ('capres', 1);
insert into pizzeria.Ingredient (name, price) values ('champignons', 1);
insert into pizzeria.Ingredient (name, price) values ('cheddar', 1);
insert into pizzeria.Ingredient (name, price) values ('chorizo', 1);
insert into pizzeria.Ingredient (name, price) values ('creme fraiche', 1);
insert into pizzeria.Ingredient (name, price) values ('emince de boeuf', 1);
insert into pizzeria.Ingredient (name, price) values ('emmental', 1);
insert into pizzeria.Ingredient (name, price) values ('fourme d\'ambert aop', 1);
insert into pizzeria.Ingredient (name, price) values ('fromage', 1);
insert into pizzeria.Ingredient (name, price) values ('fromage a raclette', 1);
insert into pizzeria.Ingredient (name, price) values ('fromage de chevre', 1);
insert into pizzeria.Ingredient (name, price) values ('fromage fondu', 1);
insert into pizzeria.Ingredient (name, price) values ('fromage grimbergen', 1);
insert into pizzeria.Ingredient (name, price) values ('fromage rapee', 1);
insert into pizzeria.Ingredient (name, price) values ('fruits de mer', 1);
insert into pizzeria.Ingredient (name, price) values ('gorgonzola', 1);
insert into pizzeria.Ingredient (name, price) values ('jambon', 1);
insert into pizzeria.Ingredient (name, price) values ('jambon italien', 1);
insert into pizzeria.Ingredient (name, price) values ('lardons fumes', 1);
insert into pizzeria.Ingredient (name, price) values ('merguez', 1);
insert into pizzeria.Ingredient (name, price) values ('mozzarella', 1);
insert into pizzeria.Ingredient (name, price) values ('oeuf', 1);
insert into pizzeria.Ingredient (name, price) values ('oignons', 1);
insert into pizzeria.Ingredient (name, price) values ('oignons rouges', 1);
insert into pizzeria.Ingredient (name, price) values ('olives', 1);
insert into pizzeria.Ingredient (name, price) values ('origan', 1);
insert into pizzeria.Ingredient (name, price) values ('pepperoni', 1);
insert into pizzeria.Ingredient (name, price) values ('persil', 1);
insert into pizzeria.Ingredient (name, price) values ('piments forts', 1);
insert into pizzeria.Ingredient (name, price) values ('piments verts', 1);
insert into pizzeria.Ingredient (name, price) values ('poivrons', 1);
insert into pizzeria.Ingredient (name, price) values ('poivron vert', 1);
insert into pizzeria.Ingredient (name, price) values ('pommes de terre', 1);
insert into pizzeria.Ingredient (name, price) values ('porc epicee', 1);
insert into pizzeria.Ingredient (name, price) values ('poulet frit', 1);
insert into pizzeria.Ingredient (name, price) values ('poulet fume', 1);
insert into pizzeria.Ingredient (name, price) values ('poulet grille', 1);
insert into pizzeria.Ingredient (name, price) values ('poulet kebab (halal)', 1);
insert into pizzeria.Ingredient (name, price) values ('provolone', 1);
insert into pizzeria.Ingredient (name, price) values ('pulled pork', 1);
insert into pizzeria.Ingredient (name, price) values ('reblochon', 1);
insert into pizzeria.Ingredient (name, price) values ('sauce a l\'ail', 1);
insert into pizzeria.Ingredient (name, price) values ('sauce au poivre', 1);
insert into pizzeria.Ingredient (name, price) values ('sauce barbecue', 1);
insert into pizzeria.Ingredient (name, price) values ('sauce chili thai', 1);
insert into pizzeria.Ingredient (name, price) values ('sauce curry douce', 1);
insert into pizzeria.Ingredient (name, price) values ('sauce tomate', 1);
insert into pizzeria.Ingredient (name, price) values ('saumon fume', 1);
insert into pizzeria.Ingredient (name, price) values ('thon', 1);
insert into pizzeria.Ingredient (name, price) values ('tomate', 1);
insert into pizzeria.Ingredient (name, price) values ('tomates fraiches', 1);
insert into pizzeria.Ingredient (name, price) values ('viande de veau fume', 1);
insert into pizzeria.Ingredient (name, price) values ('viande hachee', 1);
